---
# need to put this into a role
- hosts: localhost
  tasks:
  - name: Get Token
    uri:
      url: https://adam-dnac/api/system/v1/auth/token
      method: POST
      user: admin
      password: Grapevine1
      force_basic_auth: yes
      status_code: 200
      return_content: yes
      validate_certs: no
    register: token

  - name: Set cookie as fact
    set_fact: cookie="X-JWT-ACCESS-TOKEN={{ token.json.Token }}"

# not really required
  - name: Check cookie
    debug: var=cookie
    verbosity: 3

  - name: Get network_devices
    uri:
      url: https://adam-dnac/api/v1/network-device
      method: GET
      #return_content: yes
      validate_certs: no
      headers:
        Cookie: "{{ cookie }}"
    register: network_device

  - name: Device Details
    debug: var=network_device
