---
# need to put this into a role
- hosts: localhost

  vars_files:
    - vars.yml

  roles:
  - auth
  - { role: get, geturl: 'image/importation?name=cat3k_caa-universalk9.16.06.01.SPA.bin' }

  tasks:
  - name: show result
    debug:
     var: response