- name: Delete
  uri:
    url: 'https://{{ host.dnac }}/api/v1/{{ deleteurl }}'
    method: DELETE
    return_content: yes
    validate_certs: no
    headers:
        Cookie: "{{ cookie }}"
        Content-Type: application/json
    status_code: 202
  register: delete_response

- name: set taskId
  set_fact: taskId="{{ delete_response.json.response.taskId }}"

- name: show taskId
  debug: var=taskId