---

- name: GET
  uri:
    url: 'https://{{ dnac.host }}/api/v1/{{ geturl }}'
    method: GET
    return_content: yes
    validate_certs: no
    headers:
        Cookie: "{{ cookie }}"
    status_code: 200
  register: response_json

- name: set response
  set_fact: response="{{ response_json.json.response }}"

- name: show response
  debug:
    var: response
    verbosity: 3
